server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gyubang?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    username: root
    password: root
  redis:
    timeout: 300

JWT:
  # token生成/校验秘钥
  tokenKey: dsasadQ@WE
  dayMs: 86400000

# 微信小程序
mini:
  # 密钥
  appid: 输入你的微信AppId
  secret: 输入你的微信secret